apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Release.Name }}-{{ .Values.config.name }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-creds-{{ .Values.config.name }}
      key: creds