# apiVersion: keyvault.azure.upbound.io/v1beta2
# kind: Vault
# metadata:
#   annotations:
#     meta.upbound.io/example-id: keyvault/v1beta2/key
#   labels:
#     example-name: example
#   name: uptest-random
# spec:
#   forProvider:
#     location: West Europe
#     resourceGroupNameSelector:
#       matchLabels:
#         example-name: example
#     skuName: premium
#     softDeleteRetentionDays: 7
#     tenantId: ${data.azurerm_client_config.current.tenant_id}

# ---

apiVersion: keyvault.azure.upbound.io/v1beta2
kind: Vault
metadata:
  name: kv-{{ .Release.Name }}-{{ .Values.service.name }}
  annotations:
    meta.upbound.io/example-id: keyvault/v1beta2/key
  labels:
    kv-name: kv-{{ .Release.Name }}
spec:
  forProvider:
    skuName: premium
    location: Norway East
    tenantId: {{ .Values.tenant.id }}
    resourceGroupNameSelector:
      matchLabels:
        rg-name: rg-{{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.service.providerconfigref }}
  