apiVersion: fortedigital.com/v1alpha1
kind: FdCustomAppClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  namespace: default
  labels:
    testing.upbound.io/rg-name: rg-{{ .Release.Name }}
spec:
  id: {{ .Values.service.name }}
  compositionSelector:
    matchLabels:
      provider: azure
  providerconfig: {{ .Values.service.providerconfigref }}
  tenant: {{ .Values.tenant.id }}
