apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-{{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    testing.upbound.io/rg-name: rg-{{ .Release.Name }}
spec:
  forProvider:
    location: Norway East