apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: aks
    repoURL: https://github.com/snothub/crossplane-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

