apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: .
    repoURL: https://github.com/snothub/potential-system
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://dns-hanmxanb.hcp.norwayeast.azmk8s.io
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true